// Publish event cover images and (re)generate data/covers.generated.yml.
//
// Convention: any file in data/<year>/<slug>/images/ whose name starts with
// "cover" is that event's card cover. It wins over the event.yaml `image:`
// field, which stays as the fallback for events that have no cover yet.
//
// Like speaker images, the source of truth is data/ and only data/ is committed;
// the copies under public/img/events/<slug>/ are build artifacts (gitignored),
// so this runs before dev/build via npm pre-hooks.
//
// The runtime can't read the filesystem (static export + Workers), so the script
// also writes a small manifest, data/covers.generated.yml, which src/lib/events.ts
// imports as a raw string like it already does for events.order.yml. The manifest
// is committed — same as the generated SPEAKERS.md — so a fresh clone can
// typecheck/lint before any pre-hook has run.
//
// Run: npm run covers   (also wired to predev / prebuild / precf:build)

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import yaml from 'js-yaml';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'data');
const PUBLIC_EVENTS = path.join(ROOT, 'public/img/events');
const MANIFEST = path.join(DATA, 'covers.generated.yml');

// Raster formats we serve as-is. SVG is deliberately excluded: covers are photos.
const COVER_RE = /^cover.*\.(jpe?g|png|webp|avif)$/i;

// data/<year>/<slug>/images/ — the year and event folders are the two segments
// above images/. Folder name is the event slug (asserted by the events build).
const covers = new Map(); // slug -> { src, ext }

for (const year of fs.readdirSync(DATA, { withFileTypes: true })) {
  if (!year.isDirectory() || !/^\d{4}$/.test(year.name)) continue;
  const yearDir = path.join(DATA, year.name);
  for (const event of fs.readdirSync(yearDir, { withFileTypes: true })) {
    if (!event.isDirectory()) continue;
    const imagesDir = path.join(yearDir, event.name, 'images');
    if (!fs.existsSync(imagesDir)) continue;

    const matches = fs
      .readdirSync(imagesDir)
      .filter((f) => COVER_RE.test(f))
      .sort();
    if (matches.length === 0) continue;
    if (matches.length > 1) {
      console.warn(
        `covers: "${event.name}" has ${matches.length} cover files ` +
          `(${matches.join(', ')}) — using "${matches[0]}".`,
      );
    }
    covers.set(event.name, {
      src: path.join(imagesDir, matches[0]),
      ext: path.extname(matches[0]).toLowerCase(),
    });
  }
}

// --- publish into public/ ----------------------------------------------------
// Normalized destination name so the served path is derivable from slug + ext.
const manifest = {};
for (const [slug, { src, ext }] of [...covers].sort(([a], [b]) => a.localeCompare(b))) {
  const dest = path.join(PUBLIC_EVENTS, slug, `cover${ext}`);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  manifest[slug] = `/img/events/${slug}/cover${ext}`;
}

// Drop stale published covers for events whose source image was removed.
if (fs.existsSync(PUBLIC_EVENTS)) {
  for (const entry of fs.readdirSync(PUBLIC_EVENTS, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = path.join(PUBLIC_EVENTS, entry.name);
    for (const file of fs.readdirSync(dir)) {
      if (!/^cover\./i.test(file)) continue;
      const keep = manifest[entry.name] === `/img/events/${entry.name}/${file}`;
      if (!keep) fs.rmSync(path.join(dir, file));
    }
  }
}

fs.writeFileSync(
  MANIFEST,
  '# Generated by scripts/sync-covers.mjs — do not edit by hand.\n' +
    '# Run `npm run covers` to regenerate (also runs on predev/prebuild).\n' +
    '# Maps event slug -> served cover path, sourced from\n' +
    '# data/<year>/<slug>/images/cover*.\n' +
    (Object.keys(manifest).length
      ? yaml.dump(manifest, { lineWidth: -1, quotingType: "'" })
      : '{}\n'),
);

console.log(`covers: ${Object.keys(manifest).length} published. Wrote data/covers.generated.yml.`);
